spring.application.name: otter
spring.main.banner-mode: off
server.port: 5000
spring:
  security:
    user:
      name: demo
      password: $2a$12$O5t/midC3o3nxg0PeGqcVOMmLcPV2N7DPfJxv74ao0unOJi0rqXoy # 1234
server:
  error:
    include-stacktrace: never

server.max-http-request-header-size: 8KB

jwt:
  secret: m37dBV9J76I616HXT2jDkJ1XE9lc7R7uHXNnu1TL9Tec050jvPUNS7gkV6XOHq8ejBckVwHQHAtC7GywN1iyww==
  expires: PT1H
  refresh-expires: P7D

#logging.level:
#  'org.springframework.security.web.FilterChainProxy': TRACE
#  'org.springframework.security.web.firewall.HttpStatusRequestRejectedHandler': DEBUG

spring.mail:
  username:
  password:
  host: 'email-smtp.ap-northeast-2.amazonaws.com'
  port: 587
  properties:
    mail.smtp.ssl.enable: false
    mail.smtp.starttls.enable: true
    mail.debug: false
  sending-rate:
  from:

spring.data.redis:
  host: localhost
  port: 6379

management:
  endpoint:
    health:
      cache:
        time-to-live: 1s
      show-details: always